Update Jenkins CI/CD pipeline

diff --git a/javaapp-pipeline/Jenkinsfile b/javaapp-pipeline/Jenkinsfile
--- a/javaapp-pipeline/Jenkinsfile
+++ b/javaapp-pipeline/Jenkinsfile
@@ -1,110 +1,125 @@
 pipeline {
-    agent {label 'agent'}
+
+    agent any
+
+    options {
+        skipDefaultCheckout(true)
+    }
+
+    environment {
+        IMAGE_NAME = 'sswamy0127/jenkins-demo'
+        CONTAINER_NAME = 'jenkins-demo-app'
+    }
 
     stages {
+
         stage('Checkout') {
             steps {
-                git url: 'https://github.com/artisantek/jenkins.git'
+                git branch: 'master',
+                    url: 'https://github.com/Somashekar127/jenkins.git'
             }
         }
 
-        stage('Tests') {
-            parallel {
-                stage('Unit Tests') {
-                    steps {
-                        dir('javaapp-pipeline') {
-                            sh 'mvn clean test'
-                        }
-                    }
-                }
-                stage('Trivy Scan') {
-                    steps {
-                        dir('javaapp-pipeline') {
-                            sh '''
-                                wget -q https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O html.tpl
-                                trivy fs --format template --template "@html.tpl" -o report.html .
-                            '''
-                        }
-                    }
-                }
-            }
-        }
-
-        // stage('Sonar Analysis') {
-        //     steps {
-        //         dir('javaapp-pipeline') {
-        //             withSonarQubeEnv('sonar') {
-        //                 sh '''
-        //                     mvn clean verify sonar:sonar \
-        //                     -Dsonar.projectKey=java-app \
-        //                     -Dsonar.projectName=java-app 
-        //                 '''
-        //             }
-        //         }
-        //     }
-        // }
-
-        stage('Build') {
+        stage('Unit Tests') {
             steps {
                 dir('javaapp-pipeline') {
-                    sh 'mvn clean package'
+                    sh 'mvn clean test'
                 }
             }
         }
 
-        stage('Publish') {
+        stage('SonarQube Analysis') {
             steps {
-                script {
-                    def GROUP_ID = sh(script: "mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()
-                    def ARTIFACT_ID = sh(script: "mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()
-                    def VERSION = sh(script: "mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f javaapp-pipeline/pom.xml", returnStdout: true).trim()
-                    def GROUP_PATH = sh(script: "echo '${GROUP_ID}' | tr '.' '/'", returnStdout: true).trim()
-                    def TARGET_PATH = "maven/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}/"
-                    def JAR_PATH = "${ARTIFACT_ID}-${VERSION}.jar"
-        
-                    dir('javaapp-pipeline/target') {
-                        rtUpload(
-                            serverId: 'jfrog',
-                            spec: """{
-                                "files": [
-                                    {
-                                        "pattern": "${JAR_PATH}",
-                                        "target": "${TARGET_PATH}"
-                                    }
-                                ]
-                            }"""
-                        )
+                dir('javaapp-pipeline') {
+                    withSonarQubeEnv('sonarqube') {
+                        sh '''
+                            mvn verify sonar:sonar \
+                            -Dsonar.projectKey=jenkins-demo \
+                            -Dsonar.projectName=jenkins-demo
+                        '''
                     }
                 }
             }
         }
 
-        stage('Deploy') {
+        stage('Maven Build') {
             steps {
-                dir('javaapp-pipeline/target') {
+                dir('javaapp-pipeline') {
+                    sh 'mvn clean package -DskipTests'
+                }
+            }
+        }
+
+        stage('Docker Build') {
+            steps {
+                dir('javaapp-pipeline') {
+                    sh 'docker build -t $IMAGE_NAME:latest .'
+                }
+            }
+        }
+
+        stage('Trivy Scan') {
+            steps {
+                sh '''
+                    trivy image --exit-code 0 \
+                    --severity HIGH,CRITICAL \
+                    $IMAGE_NAME:latest
+                '''
+            }
+        }
+
+        stage('Push to Docker Hub') {
+            steps {
+                withCredentials([
+                    usernamePassword(
+                        credentialsId: 'dockerhub-creds',
+                        usernameVariable: 'DOCKER_USER',
+                        passwordVariable: 'DOCKER_PASS'
+                    )
+                ]) {
                     sh '''
-                        if pgrep -f "java -jar java-sample-21-1.0.0.jar" > /dev/null; then
-                            pkill -f "java -jar java-sample-21-1.0.0.jar"
-                            echo "App was running and has been killed."
-                        else
-                            echo "App is not running."
-                        fi
-                        JENKINS_NODE_COOKIE=dontKillMe nohup java -jar java-sample-21-1.0.0.jar > app.log 2>&1 &
+                        echo "$DOCKER_PASS" | docker login \
+                        -u "$DOCKER_USER" \
+                        --password-stdin
+
+                        docker push $IMAGE_NAME:latest
+
+                        docker logout
                     '''
                 }
             }
         }
 
+        stage('Pull Docker Image') {
+            steps {
+                sh '''
+                    docker image rm $IMAGE_NAME:latest || true
+                    docker pull $IMAGE_NAME:latest
+                '''
+            }
+        }
+
+        stage('Deploy Container') {
+            steps {
+                sh '''
+                    docker rm -f $CONTAINER_NAME || true
+
+                    docker run -d \
+                    --name $CONTAINER_NAME \
+                    -p 5000:5000 \
+                    $IMAGE_NAME:latest
+                '''
+            }
+        }
     }
-    
+
     post {
-      always {
-        cleanWs()
-      }
-      failure {
-        emailext attachLog: true, body: 'Pipeline Failed, Please check the logs', subject: 'Job Failed', to: 'artisantek.adithya@gmail.com'
-      }
+        success {
+            echo 'CI/CD Pipeline completed successfully'
+        }
+
+        failure {
+            echo 'CI/CD Pipeline failed'
+        }
     }
-
-
 }
